---
- hosts: webserver
  become: true
  tasks:
  - name: install package
    yum:
      name: "httpd"
      state: "present"
  - name: start apache server
    service:
      name: httpd
      state: started
      enable: true
  - name: deploy static website
    copy:
      content: This is first HTTPD server config through jenkins pipeline
      dest: /var/www/html/index.html
