---
- hosts: 172.31.9.214
  become: true
  tasks:
    - name: Install Apache HTTP server
      yum: name=httpd update_cache=yes state=latest
    - name: Start HTTP Server
      service: name=httpd enabled=yes state=started
    - name: welcome page
      copy:
       cotent: Hello this is the first httpd server installation through jenkins 
       dest: /var/www/html/index.html
...
